'use client';

import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Theme = 'light' | 'dark';
type Lang = 'id' | 'en';

// --- THEME ---
interface ThemeContextType {
    theme: Theme;
    toggleTheme: () => void;
}

const ThemeContext = createContext<ThemeContextType>({ theme: 'light', toggleTheme: () => { } });

export function ThemeProvider({ children }: { children: ReactNode }) {
    const [theme, setTheme] = useState<Theme>('light');

    useEffect(() => {
        const saved = localStorage.getItem('rl-theme');
        const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        const initial = saved === 'light' || saved === 'dark' ? saved : prefersDark ? 'dark' : 'light';

        document.documentElement.setAttribute('data-theme', initial);
        const timeout = window.setTimeout(() => setTheme(initial), 0);

        return () => window.clearTimeout(timeout);
    }, []);

    const toggleTheme = () => {
        const next = theme === 'light' ? 'dark' : 'light';
        setTheme(next);
        localStorage.setItem('rl-theme', next);
        document.documentElement.setAttribute('data-theme', next);
    };

    return (
        <ThemeContext.Provider value={{ theme, toggleTheme }}>
            {children}
        </ThemeContext.Provider>
    );
}

export const useTheme = () => useContext(ThemeContext);

// --- LANGUAGE ---
const translations = {
    id: {
        'login.title': 'Ryan Eko License',
        'login.subtitle': 'Admin Dashboard',
        'login.placeholder': 'Masukkan password',
        'login.button': 'Masuk',
        'login.loading': 'Memverifikasi...',
        'login.error': 'Password salah!',
        'header.title': 'Ryan Eko License',
        'header.logout': 'Keluar',
        'tab.rawFileCopy': 'RAW File Copy',
        'tab.realtimeUpload': 'Realtime Upload',
        'tab.photoSplit': 'Photo Split',
        'tab.fastpik': 'Fastpik',
        'tab.clientDesk': 'Client Desk',
        'list.total': 'Total',
        'list.available': 'Tersedia',
        'list.used': 'Digunakan',
        'list.refresh': 'Refresh',
        'list.search': 'Cari nama, email, atau serial...',
        'list.allStatus': 'Semua Status',
        'list.statusAvailable': 'Tersedia',
        'list.statusUsed': 'Digunakan',
        'list.statusRevoked': 'Dicabut',
        'list.serial': 'Serial',
        'list.status': 'Status',
        'list.name': 'Nama',
        'list.email': 'Email',
        'list.device': 'Device',
        'list.deviceId': 'Device ID',
        'list.instagram': 'Instagram',
        'list.activated': 'Diaktivasi',
        'list.actions': 'Aksi',
        'list.loading': 'Memuat...',
        'list.empty': 'Tidak ada lisensi ditemukan',
        'list.previous': 'Sebelumnya',
        'list.next': 'Selanjutnya',
        'list.page': 'Halaman',
        'list.of': 'dari',
        'list.sortNewest': 'Terbaru',
        'list.sortOldest': 'Terlama',
        'list.filterWithData': 'Ada Nama',
        'list.filterEmpty': 'Data Kosong',
        'list.filterAll': 'Semua Key',
        'list.allDevices': 'Semua Device',
        'list.filterDevice': 'Filter Device',
        'action.editDevice': 'Edit Device',
        'action.editTable': 'Edit Tabel',
        'action.reset': 'Reset',
        'action.delete': 'Hapus',
        'dialog.changeTitle': 'Edit Device',
        'dialog.changeDesc': 'Pilih platform baru untuk lisensi ini:',
        'dialog.selectPlatform': 'Pilih Platform',
        'dialog.cancel': 'Batal',
        'dialog.confirm': 'Konfirmasi',
        'dialog.processing': 'Memproses...',
        'dialog.resetTitle': 'Reset Lisensi',
        'dialog.resetDesc': 'Apakah kamu yakin ingin mereset lisensi ini? Status akan berubah menjadi "tersedia" dan data device akan dihapus.',
        'dialog.resetSerial': 'Serial',
        'dialog.resetUser': 'User',
        'dialog.deleteTitle': 'Hapus Informasi',
        'dialog.deleteDesc': 'Apakah kamu yakin ingin menghapus informasi pada serial ini? Nama, email, device, dan data lainnya akan dihapus. Serial tetap tersimpan.',
        'dialog.editTableTitle': 'Edit Tabel',
        'dialog.editTableDesc': 'Edit data serial, nama, email, dan device ID secara manual:',
        'dialog.serialKey': 'Serial Key',
        'dialog.customerName': 'Nama',
        'dialog.customerEmail': 'Email',
        'dialog.customerInstagram': 'Instagram',
        'dialog.deviceId': 'Device ID',
        'fastpik.title': 'Fastpik',
        'fastpik.desc': 'Kelola user & membership Fastpik',
        'fastpik.refresh': 'Refresh',
        'fastpik.newUser': 'User Baru',
        'fastpik.inviteTitle': 'Undang User Trial',
        'fastpik.namePlaceholder': 'Nama lengkap',
        'fastpik.emailPlaceholder': 'Email',
        'fastpik.day': 'hari',
        'fastpik.days': 'hari',
        'fastpik.sendInvite': 'Kirim Undangan',
        'fastpik.userCount': 'Total User',
        'fastpik.noUsers': 'Belum ada user',
        'fastpik.colName': 'Nama',
        'fastpik.colEmail': 'Email',
        'fastpik.colPlan': 'Paket',
        'fastpik.colExpiry': 'Kadaluarsa',
        'fastpik.colRegistered': 'Terdaftar',
        'fastpik.colLastLogin': 'Login Terakhir',
        'fastpik.colActions': 'Aksi',
        'fastpik.never': 'Selamanya',
        'fastpik.unverified': 'Belum Verifikasi',
        'fastpik.deleteTitle': 'Hapus User',
        'fastpik.deleteConfirm': 'Yakin ingin menghapus',
        'fastpik.editTitle': 'Edit Langganan',
        'fastpik.editDesc': 'Ubah langganan untuk',
        'fastpik.setExpiry': 'Masa Berlaku',
        'fastpik.save': 'Simpan',
        'fastpik.or': 'Atau',
        'fastpik.changeTier': 'Ganti Paket',
        'fastpik.change': 'Ganti',
        'fastpik.searchPlaceholder': 'Cari nama atau email...',
        'fastpik.filterAll': 'Semua',
        'clientdesk.title': 'Client Desk',
        'clientdesk.desc': 'Kelola user & membership Client Desk',
        'clientdesk.refresh': 'Refresh',
        'clientdesk.newUser': 'User Baru',
        'clientdesk.inviteTitle': 'Undang User Trial',
        'clientdesk.namePlaceholder': 'Nama lengkap',
        'clientdesk.emailPlaceholder': 'Email',
        'clientdesk.day': 'hari',
        'clientdesk.days': 'hari',
        'clientdesk.sendInvite': 'Kirim Undangan',
        'clientdesk.userCount': 'Total User',
        'clientdesk.noUsers': 'Belum ada user',
        'clientdesk.colName': 'Nama',
        'clientdesk.colEmail': 'Email',
        'clientdesk.colPlan': 'Paket',
        'clientdesk.colExpiry': 'Kadaluarsa',
        'clientdesk.colRegistered': 'Terdaftar',
        'clientdesk.colLastLogin': 'Login Terakhir',
        'clientdesk.colActions': 'Aksi',
        'clientdesk.never': 'Selamanya',
        'clientdesk.unverified': 'Belum Verifikasi',
        'clientdesk.deleteTitle': 'Hapus User',
        'clientdesk.deleteConfirm': 'Yakin ingin menghapus',
        'clientdesk.editTitle': 'Edit Langganan',
        'clientdesk.editDesc': 'Ubah langganan untuk',
        'clientdesk.setExpiry': 'Masa Berlaku',
        'clientdesk.save': 'Simpan',
        'clientdesk.or': 'Atau',
        'clientdesk.changeTier': 'Ganti Paket',
        'clientdesk.change': 'Ganti',
        'clientdesk.searchPlaceholder': 'Cari nama atau email...',
        'clientdesk.filterAll': 'Semua',
        'clientdesk.assign': 'Assign',
        'clientdesk.reassign': 'Reassign',
        'clientdesk.assignTitle': 'Assign Tenant',
        'clientdesk.reassignTitle': 'Reassign Tenant',
        'clientdesk.assignDesc': 'Pilih tenant untuk akun',
        'clientdesk.currentTenant': 'Tenant Saat Ini',
        'clientdesk.noTenantAssigned': 'Belum diassign',
        'clientdesk.selectTenant': 'Pilih Tenant',
        'clientdesk.tenantRequired': 'Tenant wajib dipilih',
        'clientdesk.assignSave': 'Simpan Assignment',
        'clientdesk.assigning': 'Menyimpan...',
        'clientdesk.assignSuccess': 'Tenant account berhasil diupdate',
        'clientdesk.assignFailed': 'Gagal update tenant account',
        'tab.generate': 'Generate Serial',
        'tab.universitas': 'Universitas',
        'generate.title': 'Generate Serial Key',
        'generate.desc': 'Buat serial key baru untuk produk yang dipilih. Serial akan otomatis tersimpan ke database.',
        'generate.product': 'Pilih Produk',
        'generate.selectProduct': 'Pilih produk...',
        'generate.count': 'Jumlah Serial',
        'generate.button': 'Generate Serial',
        'generate.generating': 'Generating...',
        'generate.success': 'Serial berhasil dibuat!',
        'generate.copied': 'Tersalin!',
        'generate.copyAll': 'Salin Semua',
        'generate.copyHash': 'Salin + Hash',
        'generate.serialKey': 'Serial Key',
        'generate.sha256': 'SHA256 Hash',
        'generate.viewDB': 'Lihat di Database',
        'generate.preview': 'Preview Serial',
        'generate.previewDesc': 'Belum tersimpan ke database',
        'generate.saveDB': 'Simpan ke Database',
        'generate.savingDB': 'Menyimpan...',
        'generate.saved': 'Berhasil disimpan ke database!',
        'home.title': 'Ryan Eko License',
        'home.subtitle': 'License Management System',
        'home.admin': 'Admin Dashboard',
        'home.webhook': 'Webhook Status',
        'home.webhookTest': 'Webhook Tester',
        'home.products': 'Produk yang Didukung',
        'home.panel': 'Panel Layanan',
        'home.database': 'Database',
        'tab.panel': 'Panel',
        'panel.title': 'Panel Layanan',
        'panel.desc': 'Akses cepat ke berbagai dashboard dan layanan eksternal.',
        'database.title': 'Database',
        'database.subtitle': 'Kelola master data aplikasi',
        'database.universitiesTitle': 'Universitas',
        'database.universitiesDesc': 'Kelola nama universitas dan singkatannya.',
        'database.refresh': 'Refresh',
        'database.add': 'Tambah Universitas',
        'database.search': 'Cari nama atau singkatan...',
        'database.total': 'Total Universitas',
        'database.empty': 'Belum ada data universitas',
        'database.colName': 'Nama',
        'database.colAbbreviation': 'Singkatan',
        'database.colCreatedAt': 'Dibuat',
        'database.colActions': 'Aksi',
        'database.edit': 'Edit',
        'database.delete': 'Hapus',
        'database.createTitle': 'Tambah Universitas',
        'database.editTitle': 'Edit Universitas',
        'database.formName': 'Nama Universitas',
        'database.formAbbreviation': 'Singkatan',
        'database.formSave': 'Simpan',
        'database.formSaving': 'Menyimpan...',
        'database.deleteTitle': 'Hapus Universitas',
        'database.deleteDesc': 'Yakin ingin menghapus data universitas ini secara permanen?',
        'database.cancel': 'Batal',
        'database.created': 'Universitas berhasil ditambahkan',
        'database.updated': 'Universitas berhasil diperbarui',
        'database.deleted': 'Universitas berhasil dihapus',
        'database.required': 'Nama dan singkatan wajib diisi',
        'database.duplicate': 'Singkatan sudah digunakan universitas lain',
        'database.duplicateName': 'Nama universitas sudah ada',
        'database.upgraded': 'Data universitas lama berhasil dilengkapi singkatannya',
        'database.rowsPerPage': 'Baris per halaman',
        'database.page': 'Halaman',
        'database.prev': 'Sebelumnya',
        'database.next': 'Berikutnya',
        'tab.vendorFastpik': 'Vendor Fastpik',
        'tab.vendorClientDesk': 'Vendor Client Desk',
        'vendor.title': 'Vendor Fastpik',
        'vendor.desc': 'Kelola vendor/tenant multi-domain Fastpik',
        'vendorClientDesk.title': 'Vendor Client Desk',
        'vendorClientDesk.desc': 'Kelola vendor/tenant multi-domain Client Desk',
        'vendor.newVendor': 'Vendor Baru',
        'vendor.totalVendors': 'Total Vendor',
        'vendor.noVendors': 'Belum ada vendor',
        'vendor.since': 'Sejak',
        'vendor.deactivate': 'Nonaktifkan',
        'vendor.activate': 'Aktifkan',
        'vendor.editTitle': 'Edit Vendor',
        'vendor.editDesc': 'Ubah konfigurasi vendor',
        'vendor.createTitle': 'Tambah Vendor Baru',
        'vendor.createDesc': 'Daftarkan vendor baru dengan domain khusus',
        'vendor.formName': 'Nama Vendor',
        'vendor.formDomain': 'Domain',
        'vendor.formLogo': 'URL Logo',
        'vendor.formFavicon': 'URL Favicon',
        'vendor.formColor': 'Warna Brand',
        'vendor.formFooter': 'Teks Footer',
        'vendor.preview': 'Preview',
        'vendor.create': 'Buat',
        'vendor.created': 'Vendor berhasil dibuat!',
        'vendor.updated': 'Vendor berhasil diperbarui!',
        'vendor.delete': 'Hapus',
        'vendor.deleteTitle': 'Hapus Vendor',
        'vendor.deleteDesc': 'Yakin ingin menghapus vendor ini secara permanen?',
        'vendor.deleted': 'Vendor berhasil dihapus!',
        'vendor.deleteFailed': 'Gagal menghapus vendor',
        'vendor.apiKeyNeeded': 'Masukkan API Key untuk mengelola vendor',
    },
    en: {
        'login.title': 'Ryan Eko License',
        'login.subtitle': 'Admin Dashboard',
        'login.placeholder': 'Enter password',
        'login.button': 'Login',
        'login.loading': 'Verifying...',
        'login.error': 'Wrong password!',
        'header.title': 'Ryan Eko License',
        'header.logout': 'Logout',
        'tab.rawFileCopy': 'RAW File Copy',
        'tab.realtimeUpload': 'Realtime Upload',
        'tab.photoSplit': 'Photo Split',
        'tab.fastpik': 'Fastpik',
        'tab.clientDesk': 'Client Desk',
        'list.total': 'Total',
        'list.available': 'Available',
        'list.used': 'Used',
        'list.refresh': 'Refresh',
        'list.search': 'Search name, email, or serial...',
        'list.allStatus': 'All Status',
        'list.statusAvailable': 'Available',
        'list.statusUsed': 'Used',
        'list.statusRevoked': 'Revoked',
        'list.serial': 'Serial',
        'list.status': 'Status',
        'list.name': 'Name',
        'list.email': 'Email',
        'list.device': 'Device',
        'list.deviceId': 'Device ID',
        'list.instagram': 'Instagram',
        'list.activated': 'Activated',
        'list.actions': 'Actions',
        'list.loading': 'Loading...',
        'list.empty': 'No licenses found',
        'list.previous': 'Previous',
        'list.next': 'Next',
        'list.page': 'Page',
        'list.of': 'of',
        'list.sortNewest': 'Newest',
        'list.sortOldest': 'Oldest',
        'list.filterWithData': 'Has Data',
        'list.filterEmpty': 'Empty',
        'list.filterAll': 'All Keys',
        'list.allDevices': 'All Devices',
        'list.filterDevice': 'Filter Device',
        'action.editDevice': 'Edit Device',
        'action.editTable': 'Edit Table',
        'action.reset': 'Reset',
        'action.delete': 'Delete',
        'dialog.changeTitle': 'Edit Device',
        'dialog.changeDesc': 'Select a new platform for this license:',
        'dialog.selectPlatform': 'Select Platform',
        'dialog.cancel': 'Cancel',
        'dialog.confirm': 'Confirm',
        'dialog.processing': 'Processing...',
        'dialog.resetTitle': 'Reset License',
        'dialog.resetDesc': 'Are you sure you want to reset this license? The status will change to "available" and device data will be cleared.',
        'dialog.resetSerial': 'Serial',
        'dialog.resetUser': 'User',
        'dialog.deleteTitle': 'Clear Information',
        'dialog.deleteDesc': 'Are you sure you want to clear the information on this serial? Name, email, device, and other data will be removed. The serial key will remain.',
        'dialog.editTableTitle': 'Edit Table',
        'dialog.editTableDesc': 'Manually edit serial, name, email, and device ID:',
        'dialog.serialKey': 'Serial Key',
        'dialog.customerName': 'Name',
        'dialog.customerEmail': 'Email',
        'dialog.customerInstagram': 'Instagram',
        'dialog.deviceId': 'Device ID',
        'fastpik.title': 'Fastpik',
        'fastpik.desc': 'Manage Fastpik users & membership',
        'fastpik.refresh': 'Refresh',
        'fastpik.newUser': 'New User',
        'fastpik.inviteTitle': 'Invite Trial User',
        'fastpik.namePlaceholder': 'Full name',
        'fastpik.emailPlaceholder': 'Email',
        'fastpik.day': 'day',
        'fastpik.days': 'days',
        'fastpik.sendInvite': 'Send Invite',
        'fastpik.userCount': 'Total Users',
        'fastpik.noUsers': 'No users found',
        'fastpik.colName': 'Name',
        'fastpik.colEmail': 'Email',
        'fastpik.colPlan': 'Plan',
        'fastpik.colExpiry': 'Expiry',
        'fastpik.colRegistered': 'Registered',
        'fastpik.colLastLogin': 'Last Login',
        'fastpik.colActions': 'Actions',
        'fastpik.never': 'Never',
        'fastpik.unverified': 'Unverified',
        'fastpik.deleteTitle': 'Delete User',
        'fastpik.deleteConfirm': 'Are you sure you want to delete',
        'fastpik.editTitle': 'Edit Subscription',
        'fastpik.editDesc': 'Modify subscription for',
        'fastpik.setExpiry': 'Expiry Date',
        'fastpik.save': 'Save',
        'fastpik.or': 'Or',
        'fastpik.changeTier': 'Change Plan',
        'fastpik.change': 'Change',
        'fastpik.searchPlaceholder': 'Search name or email...',
        'fastpik.filterAll': 'All',
        'clientdesk.title': 'Client Desk',
        'clientdesk.desc': 'Manage Client Desk users & membership',
        'clientdesk.refresh': 'Refresh',
        'clientdesk.newUser': 'New User',
        'clientdesk.inviteTitle': 'Invite Trial User',
        'clientdesk.namePlaceholder': 'Full name',
        'clientdesk.emailPlaceholder': 'Email',
        'clientdesk.day': 'day',
        'clientdesk.days': 'days',
        'clientdesk.sendInvite': 'Send Invite',
        'clientdesk.userCount': 'Total Users',
        'clientdesk.noUsers': 'No users found',
        'clientdesk.colName': 'Name',
        'clientdesk.colEmail': 'Email',
        'clientdesk.colPlan': 'Plan',
        'clientdesk.colExpiry': 'Expiry',
        'clientdesk.colRegistered': 'Registered',
        'clientdesk.colLastLogin': 'Last Login',
        'clientdesk.colActions': 'Actions',
        'clientdesk.never': 'Never',
        'clientdesk.unverified': 'Unverified',
        'clientdesk.deleteTitle': 'Delete User',
        'clientdesk.deleteConfirm': 'Are you sure you want to delete',
        'clientdesk.editTitle': 'Edit Subscription',
        'clientdesk.editDesc': 'Modify subscription for',
        'clientdesk.setExpiry': 'Expiry Date',
        'clientdesk.save': 'Save',
        'clientdesk.or': 'Or',
        'clientdesk.changeTier': 'Change Plan',
        'clientdesk.change': 'Change',
        'clientdesk.searchPlaceholder': 'Search name or email...',
        'clientdesk.filterAll': 'All',
        'clientdesk.assign': 'Assign',
        'clientdesk.reassign': 'Reassign',
        'clientdesk.assignTitle': 'Assign Tenant',
        'clientdesk.reassignTitle': 'Reassign Tenant',
        'clientdesk.assignDesc': 'Select tenant for account',
        'clientdesk.currentTenant': 'Current Tenant',
        'clientdesk.noTenantAssigned': 'Not assigned yet',
        'clientdesk.selectTenant': 'Select Tenant',
        'clientdesk.tenantRequired': 'Tenant is required',
        'clientdesk.assignSave': 'Save Assignment',
        'clientdesk.assigning': 'Saving...',
        'clientdesk.assignSuccess': 'Tenant account updated successfully',
        'clientdesk.assignFailed': 'Failed to update tenant account',
        'tab.generate': 'Generate Serial',
        'tab.universitas': 'University',
        'generate.title': 'Generate Serial Key',
        'generate.desc': 'Create new serial keys for the selected product. Serials are saved to database automatically.',
        'generate.product': 'Select Product',
        'generate.selectProduct': 'Select product...',
        'generate.count': 'Number of Serials',
        'generate.button': 'Generate Serial',
        'generate.generating': 'Generating...',
        'generate.success': 'Serials generated successfully!',
        'generate.copied': 'Copied!',
        'generate.copyAll': 'Copy All',
        'generate.copyHash': 'Copy + Hash',
        'generate.serialKey': 'Serial Key',
        'generate.sha256': 'SHA256 Hash',
        'generate.viewDB': 'View in Database',
        'generate.preview': 'Serial Preview',
        'generate.previewDesc': 'Not yet saved to database',
        'generate.saveDB': 'Save to Database',
        'generate.savingDB': 'Saving...',
        'generate.saved': 'Successfully saved to database!',
        'home.title': 'Ryan Eko License',
        'home.subtitle': 'License Management System',
        'home.admin': 'Admin Dashboard',
        'home.webhook': 'Webhook Status',
        'home.webhookTest': 'Webhook Tester',
        'home.products': 'Supported Products',
        'home.panel': 'Service Panel',
        'home.database': 'Database',
        'tab.panel': 'Panel',
        'panel.title': 'Service Panel',
        'panel.desc': 'Quick access to various dashboards and external services.',
        'database.title': 'Database',
        'database.subtitle': 'Manage application master data',
        'database.universitiesTitle': 'Universities',
        'database.universitiesDesc': 'Manage university names and abbreviations.',
        'database.refresh': 'Refresh',
        'database.add': 'Add University',
        'database.search': 'Search name or abbreviation...',
        'database.total': 'Total Universities',
        'database.empty': 'No universities found',
        'database.colName': 'Name',
        'database.colAbbreviation': 'Abbreviation',
        'database.colCreatedAt': 'Created',
        'database.colActions': 'Actions',
        'database.edit': 'Edit',
        'database.delete': 'Delete',
        'database.createTitle': 'Add University',
        'database.editTitle': 'Edit University',
        'database.formName': 'University Name',
        'database.formAbbreviation': 'Abbreviation',
        'database.formSave': 'Save',
        'database.formSaving': 'Saving...',
        'database.deleteTitle': 'Delete University',
        'database.deleteDesc': 'Are you sure you want to permanently delete this university?',
        'database.cancel': 'Cancel',
        'database.created': 'University created successfully',
        'database.updated': 'University updated successfully',
        'database.deleted': 'University deleted successfully',
        'database.required': 'Name and abbreviation are required',
        'database.duplicate': 'Abbreviation is already used by another university',
        'database.duplicateName': 'University name already exists',
        'database.upgraded': 'Existing university was updated with the new abbreviation',
        'database.rowsPerPage': 'Rows per page',
        'database.page': 'Page',
        'database.prev': 'Previous',
        'database.next': 'Next',
        'tab.vendorFastpik': 'Vendor Fastpik',
        'tab.vendorClientDesk': 'Vendor Client Desk',
        'vendor.title': 'Vendor Fastpik',
        'vendor.desc': 'Manage multi-domain Fastpik vendors/tenants',
        'vendorClientDesk.title': 'Vendor Client Desk',
        'vendorClientDesk.desc': 'Manage multi-domain Client Desk vendors/tenants',
        'vendor.newVendor': 'New Vendor',
        'vendor.totalVendors': 'Total Vendors',
        'vendor.noVendors': 'No vendors found',
        'vendor.since': 'Since',
        'vendor.deactivate': 'Deactivate',
        'vendor.activate': 'Activate',
        'vendor.editTitle': 'Edit Vendor',
        'vendor.editDesc': 'Modify vendor configuration',
        'vendor.createTitle': 'Add New Vendor',
        'vendor.createDesc': 'Register a new vendor with custom domain',
        'vendor.formName': 'Vendor Name',
        'vendor.formDomain': 'Domain',
        'vendor.formLogo': 'Logo URL',
        'vendor.formFavicon': 'Favicon URL',
        'vendor.formColor': 'Brand Color',
        'vendor.formFooter': 'Footer Text',
        'vendor.preview': 'Preview',
        'vendor.create': 'Create',
        'vendor.created': 'Vendor created successfully!',
        'vendor.updated': 'Vendor updated successfully!',
        'vendor.delete': 'Delete',
        'vendor.deleteTitle': 'Delete Vendor',
        'vendor.deleteDesc': 'Are you sure you want to permanently delete this vendor?',
        'vendor.deleted': 'Vendor deleted successfully!',
        'vendor.deleteFailed': 'Failed to delete vendor',
        'vendor.apiKeyNeeded': 'Enter API Key to manage vendors',
    },
} as const;

type TranslationKey = keyof typeof translations.id;

interface LangContextType {
    lang: Lang;
    toggleLang: () => void;
    t: (key: TranslationKey) => string;
}

const LangContext = createContext<LangContextType>({
    lang: 'id',
    toggleLang: () => { },
    t: (key) => key,
});

export function LangProvider({ children }: { children: ReactNode }) {
    const [lang, setLang] = useState<Lang>('id');

    useEffect(() => {
        const saved = localStorage.getItem('rl-lang');
        if (saved !== 'id' && saved !== 'en') return;

        const timeout = window.setTimeout(() => setLang(saved), 0);
        return () => window.clearTimeout(timeout);
    }, []);

    const toggleLang = () => {
        const next = lang === 'id' ? 'en' : 'id';
        setLang(next);
        localStorage.setItem('rl-lang', next);
    };

    const t = (key: TranslationKey): string => {
        return translations[lang][key] || key;
    };

    return (
        <LangContext.Provider value={{ lang, toggleLang, t }}>
            {children}
        </LangContext.Provider>
    );
}

export const useLang = () => useContext(LangContext);
